controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

prometheus_bundle_prometheus:
    path: /metrics/prometheus
    controller: Artprima\PrometheusMetricsBundle\Controller\MetricsController::prometheus