global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'symfony-app'
    static_configs:
      - targets: ['symfony-app:80']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s