---
name: Grafana Integration Screenshots

on:
  pull_request:
    branches: [master]
    paths:
      - 'grafana/**'
      - 'demo/**'
      - '.github/workflows/grafana-integration.yml'
  push:
    branches: [master]
    paths:
      - 'grafana/**'
      - 'demo/**'
      - '.github/workflows/grafana-integration.yml'
  workflow_dispatch:

jobs:
  grafana-integration:
    runs-on: ubuntu-latest
    name: Generate Grafana Dashboard Screenshots

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js for Puppeteer
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer dependencies
        run: |
          npm init -y
          npm install puppeteer
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Setup Grafana provisioning
        run: |
          ./.github/scripts/setup-grafana-provisioning.sh

      - name: Start Docker services
        run: |
          cd demo
          docker compose up -d --build

          # Wait for services to be healthy
          echo "Waiting for services to be ready..."
          sleep 30

          # Check service status
          echo "=== Docker Services Status ==="
          docker compose ps
          
          echo "=== Service Logs ==="
          docker compose logs --tail=20
          
          # Test service connectivity
          echo "=== Testing Service Connectivity ==="
          for i in {1..10}; do
            echo "Attempt $i/10..."
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "✓ Symfony app is responding"
              break
            else
              echo "⚠ Symfony app not ready yet..."
              sleep 3
            fi
          done
          
          for i in {1..10}; do
            echo "Attempt $i/10..."
            if curl -s http://localhost:9090/-/ready > /dev/null; then
              echo "✓ Prometheus is ready"
              break
            else
              echo "⚠ Prometheus not ready yet..."
              sleep 3
            fi
          done
          
          for i in {1..10}; do
            echo "Attempt $i/10..."
            if curl -s http://localhost:3000/api/health > /dev/null; then
              echo "✓ Grafana is ready"
              break
            else
              echo "⚠ Grafana not ready yet..."
              sleep 3
            fi
          done

      - name: Generate test traffic
        run: |
          ./.github/scripts/generate-traffic.sh

          # Wait a bit for metrics to be scraped
          sleep 15

      - name: Verify Prometheus is collecting metrics
        run: |
          echo "Checking Prometheus metrics..."
          curl -s "http://localhost:9090/api/v1/query?query=symfony_http_requests_total" | jq '.' || true

          echo "Checking if Grafana can reach Prometheus..."
          curl -s "http://localhost:3000/api/datasources/proxy/1/api/v1/query?query=up" | head -20 || true

      - name: Debug services status before screenshots
        run: |
          echo "=== Service Status ==="
          docker compose -f demo/docker-compose.yml ps
          
          echo "=== Grafana Health Check ==="
          curl -s "http://localhost:3000/api/health" | jq '.' || true
          
          echo "=== Available Dashboards ==="
          curl -s -u admin:admin "http://localhost:3000/api/search?type=dash-db" | jq '.' || true
          
          echo "=== Prometheus Targets ==="
          curl -s "http://localhost:9090/api/v1/targets" | jq '.data.activeTargets' || true

      - name: Capture live dashboard screenshots
        run: |
          xvfb-run -a node .github/scripts/capture-screenshots.js

      - name: Verify screenshots were created
        run: |
          ls -la screenshots/
          file screenshots/*.png || true

      - name: Stop Docker services
        run: |
          cd demo
          docker compose down
          docker compose logs --tail=50 || true

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: grafana-dashboard-screenshots
          path: screenshots/
          retention-days: 30

      - name: Upload service logs for debugging
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: service-logs
          path: demo/
          retention-days: 7
