name: Symfony

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: ubuntu-latest
            php-version: '8.2'
            symfony-version: '5.4'
            symfony-require: '5.4.*'
            phpunit-bridge-version: '5.4.*'
          - operating-system: ubuntu-latest
            php-version: '8.2'
            symfony-version: '6.4'
            symfony-require: '6.4.*'
            phpunit-bridge-version: '6.4.*'
          - operating-system: ubuntu-latest
            php-version: '8.5'
            symfony-version: '6.4'
            symfony-require: '6.4.*'
            phpunit-bridge-version: '6.4.*'
          - operating-system: ubuntu-latest
            php-version: '8.2'
            symfony-version: '7.4'
            symfony-require: '7.4.*'
            phpunit-bridge-version: '7.4.*'
          - operating-system: ubuntu-latest
            php-version: '8.5'
            symfony-version: '7.4'
            symfony-require: '7.4.*'
            phpunit-bridge-version: '7.4.*'
          - operating-system: ubuntu-latest
            php-version: '8.4'
            symfony-version: '8.0'
            symfony-require: '8.0.*'
            phpunit-bridge-version: '8.0.*'
          - operating-system: ubuntu-latest
            php-version: '8.5'
            symfony-version: '8.0'
            symfony-require: '8.0.*'
            phpunit-bridge-version: '8.0.*'
    name: PHP ${{ matrix.php-version }} / Symfony ${{ matrix.symfony-version }} Test on ${{ matrix.operating-system }}
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-require }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, redis
        ini-values: post_max_size=256M
        coverage: xdebug
        tools: php-cs-fixer, phpunit
    - name: Download Symfony CLI
      run: curl -sS https://get.symfony.com/cli/installer | bash
    - name: Install Symfony
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        $HOME/.symfony5/bin/symfony new symfony --version="${{ matrix.symfony-require }}"
    - name: Configure Symfony to run integration tests
      run: |
        php .integration/patch.php
        cd symfony
        composer require symfony/phpunit-bridge:${{ matrix.phpunit-bridge-version }} -n --no-progress
        composer require symfony/browser-kit:${{ matrix.symfony-require }} -n --no-progress
        composer require artprima/prometheus-metrics-bundle:* -n --no-progress --no-scripts
        cp -rf ../.integration/symfony/* ./
        composer update -n --no-progress
    - name: Run Integration tests
      run: |
        cd symfony
        php bin/phpunit
